# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
markdown: kramdown
title: I'm a Big Boy Now

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: I'm a Big Boy Now

description: Personal Transformation, Computer Science, and Software Development.
author:
  name: Brandon Keown
  email: me@brandonkeown.com
  github: theqabalist
  twitter: emptylambda
  linkedin: brandonkeown
  bio: ''
  email_md5: 4398c3db5a25f7dc1f4397eebefec571

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
